name: Deploy Go Docs

on:
  push:
    branches: [ "main" ]

permisions:
  contents: write

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'

    - name: Install pkgsite
      run: go install golang.org/x/pkgsite/cmd/pkgsite@latest

    - name: Generate Documentation
      run : |
        mkdir docs 
        nohup pkgsite -http :6060 & 
        sleep 5
        wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -P docs http://localhost:6060/github.com/AarC10/GSW-V2
  
    - name: Disable Jekyll (add .nojekyll)
      run: |
        touch docs/.nojekyll


    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
      folder: ./docs
      clean: true

