name: Deploy Go Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Install pkgsite
        run: go install golang.org/x/pkgsite/cmd/pkgsite@latest

      - name: Generate static documentation
        run: |
          mkdir -p docs
          nohup pkgsite -listen=:6060 &
          sleep 5
          wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -P docs http://localhost:6060/pkg/yourmodule

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          clean: true

