name: Documentation

on: [push]

concurrency:
  group: publish-wiki.yml
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      # Pulls repo
      - uses: actions/checkout@v1

      # Ensures Go installed
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'

      # Installs gomarkdoc
      - name: Install gomarkdoc
        run: go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest
      
      # Generates wiki with gomarkdoc
      - name: Generate Wiki Documentation
        run: |
          rm -rf wiki/* 
          mkdir -p wiki
          for dir in $(go list -f '{{.Dir}}' ./... | grep -v "cmd"); do
            gomarkdoc --output "./Docs/wiki/$(basename $dir).md" $dir
          done
      # Uploads wiki directory to github wiki page
      - name: Upload Documentation to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4        
